### ISSUE TITLE
Server will not load

### ISSUE THREAD

**Issue by AvatarMental** [naturecodevoid/voicechat-discord#24]
**Describe the bug**
Server will not start after adding token and channel ID

**To Reproduce**
Create bot as per instructions and invite to server.
Add bot token and channel ID
Try to start server.

**Expected behavior**
Server should start.

**Screenshots**

**Logs**
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'voicechat-discord'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-1.20.1.jar:0.11.2]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.LinkedHashMap.get(Object)" is null
	at dev.naturecodevoid.voicechatdiscord.Core.loadConfig(Core.java:85) ~[voicechat-discord-fabric-2.1.0.jar:?]
	at dev.naturecodevoid.voicechatdiscord.Core.enable(Core.java:36) ~[voicechat-discord-fabric-2.1.0.jar:?]
	at dev.naturecodevoid.voicechatdiscord.FabricMod.onInitializeServer(FabricMod.java:24) ~[voicechat-discord-fabric-2.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more.

**Versions (please complete the following information):**
- Minecraft: 
- Loader (paper, purpur, fabric, quilt, etc): 
- Simple Voice Chat: 
- Simple Voice Chat Discord Bridge: 

**Additional context**

**Comment by naturecodevoid** [comment]
Something is wrong with your config. You are most likely missing the vc_id property. This should be handled better in the future
