### ISSUE TITLE
Not working with my spigot server

### ISSUE THREAD

**Issue by LukDun** [naturecodevoid/voicechat-discord#29]
Hey, I am having an issue with the mod not loading on my Spigot server where I can't get it to work at all and it gives me the error every time the server starts.

**To Reproduce**
1. Put mod into server plugins folder.
2. Change configs how it says on modrinth.
3. Setup Bot.
4. Start Server.
5. It gives the error below ↓ in server logs.

**Expected behavior**
It should just show how it loaded the plugin and then it works but it doesn't.

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/117318790/7faa111a-d24e-4475-932e-025110d5f838)

**Logs**
First, set `debug_level` to `3` (or `2` if there's too much spam) in the Simple Voice Chat Discord Bridge configuration file. After restarting your server or using `/dvc reloadconfig`, please upload the server logs here (make sure they don't include any sensitive info).
Done then the logs look like this, https://mclo.gs/Iz3mOFU That is a share link to the Aternos logs (the server is hosted with the website Aternos). For this with the changed debug level the error is from line 193 to 206.

**Versions (please complete the following information):**
- Minecraft: 1.19.4 
- Loader: Spigot 
- Simple Voice Chat: 2.4.11 I've also tried 2.4.15 and 2.4.8
- Simple Voice Chat Discord Bridge: 2.1.0

**Additional context**

Logs showing the error (before the debug level change) Lines 235-249:
[07:53:01] [Server thread/ERROR]: [voicechat-discord] Plugin voicechat-discord v2.1.0 has failed to register events for class dev.naturecodevoid.voicechatdiscord.PaperPlugin because com/destroystokyo/paper/event/brigadier/CommandRegisteredEvent does not exist.
[07:53:01] [Server thread/ERROR]: Error occurred while enabling voicechat-discord v2.1.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandMap org.bukkit.Server.getCommandMap()'
at dev.naturecodevoid.voicechatdiscord.PaperPlugin.onEnable(PaperPlugin.java:69) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by naturecodevoid** [comment]
Will look into this next time I work on the project

**Comment by LukDun** [comment]
> Will look into this next time I work on the project

Thank you no rush tho. Just don't know if it is a bug or something I missed in setup.

**Comment by naturecodevoid** [comment]
It's a bug

**Comment by naturecodevoid** [comment]
Can't believe I didn't catch this earlier. **This plugin is Paper or Purpur only.** Spigot is not supported (and will most likely never be supported after 1.2.0). The last release that supported Spigot was 1.2.0: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/1.2.0
