### ISSUE TITLE
An unexpected error occurred trying to execute that command

### ISSUE THREAD

**Issue by Kirkezz** [naturecodevoid/voicechat-discord#33]
**Describe the bug**
Hi! I have this error when I try to execute any /dvc command: 'An unexpected error occurred trying to execute that command' 

**Logs**                                                                                           
[10:48:58] [Server thread/INFO]: Starting minecraft server version 1.20.1
[10:48:58] [Server thread/INFO]: Loading properties
[10:48:58] [Server thread/INFO]: Default game type: SURVIVAL
[10:48:58] [Server thread/INFO]: Generating keypair
[10:48:58] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:48:58] [Server thread/INFO]: Using epoll channel type
[10:48:58] [Server thread/INFO]: Preparing level "world"
[10:49:00] [DefaultDispatcher-worker-1/INFO]: Registry insert complete
[10:49:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:49:18] [Worker-Main-1/INFO]: Preparing spawn area: 0%
...
[10:49:20] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[10:49:22] [Server thread/INFO]: Time elapsed: 12706 ms
[10:49:22] [Server thread/INFO]: Done (23.394s)! For help, type "help"
[10:49:22] [Server thread/INFO]: Starting remote control listener
[10:49:22] [Server thread/INFO]: Thread RCON Listener started
[10:49:22] [Server thread/INFO]: RCON running on 0.0.0.0:25575
[10:49:22] [VoiceChatServerThread/INFO]: [voicechat] Voice chat server started at [server-ip-redacted]:24454
[10:49:24] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2021ms or 40 ticks behind
[10:49:49] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
[10:49:55] [Server thread/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2561$class_2562.fromJson(dev.naturecodevoid.voicechatdiscord.shadow.gson.JsonElement)'
[10:49:55] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:110)
[10:49:55] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:70)
[10:49:55] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands.start(SubCommands.java:87)
[10:49:55] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[10:49:55] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_9249(class_2170.java:287)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_44252(class_2170.java:280)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_20799(class_3176.java:527)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5386(class_1255.java:67)
[10:49:55] [Server thread/INFO]: [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:156)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:130)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18857(class_1255.java:139)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[10:49:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[10:49:55] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
my config file looks like this:
bots:
- token: **********
  vc_id: 11652466248********
alert_ops_of_updates: true
debug_level: 3

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader: fabric
- Simple Voice Chat: 2.4.24 (I also tried other versions like for example 2.4.11)
- Simple Voice Chat Discord Bridge: 2.1.0 downloaded from modrinth

**Comment by naturecodevoid** [comment]
Duplicate and fixed. I just haven't pushed the update, but I probably will today

**Comment by naturecodevoid** [comment]
2.1.1 is now out with the fix
