### ISSUE TITLE
`/dvc group list` throws "unexpected error"

### ISSUE THREAD

**Issue by dustindmiller** [naturecodevoid/voicechat-discord#39]
Trying to use `/dvc group list` responds with `an unexpected error occurred trying to execute that command` everytime from all clients. (screenshots attached)

<img width="719" alt="Screenshot 2024-01-25 at 6 42 26 PM" src="https://github.com/naturecodevoid/voicechat-discord/assets/77062265/0600622b-b86b-4e30-a4f7-da32891ca9fb">
<img width="1179" alt="Screenshot 2024-01-25 at 6 40 29 PM" src="https://github.com/naturecodevoid/voicechat-discord/assets/77062265/4cb65e6b-0015-40c7-8388-6789a566e520">

**Comment by dustindmiller** [comment]
Section of the console log when command was used:
`[18:34:44] [Thread-1814/INFO]: Using 1 bot
[18:34:54] [Thread-1820/INFO]: Login Successful!
[18:34:54] [JDA MainWS-ReadThread/INFO]: Connected to WebSocket
[18:34:54] [JDA MainWS-ReadThread/INFO]: Finished Loading!
[18:34:54] [Thread-1820/INFO]: Started voice chat for DustRyDeux in channel 𝘾𝙝𝙖𝙣𝙇𝙖𝙣𝙙 SVC-Bridge-1
[18:35:02] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "players" is null
[18:35:02] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands$GroupCommands.list(SubCommands.java:260)
[18:35:02] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[18:35:02] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_9249(class_2170.java:287)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_45010(class_3244.java:1341)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_44356(class_3244.java:1321)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5386(class_1255.java:67)
[18:35:02] [Server thread/INFO]: [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:156)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:130)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5383(class_1255.java:115)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zcl000$carpet$modifiedRunLoop(MinecraftServer.java:9451)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[18:35:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[18:35:02] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:840)
[18:38:33] [Server thread/INFO]: DustRyDeux lost connection: Disconnected
[18:38:33] [Server thread/INFO]: DustRyDeux left the game
[18:38:33] [Server thread/INFO]: [voicechat] Disconnecting client DustRyDeux`

**Comment by dustindmiller** [comment]
(last comment I swear) but using `/dvc group join #` does seem to work, so they're indexed and accessible, just not showing up as a list for users.

**Comment by naturecodevoid** [comment]
Minecraft version and mod loader / server software?

**Comment by dustindmiller** [comment]
1.20.1
Fabric Server
Vanilla Clients, Forge Clients and Fabric Clients

**Comment by naturecodevoid** [comment]
Will look into this next time I work on the mod (although that likely won't be for a while)

**Comment by naturecodevoid** [comment]
Update: https://github.com/naturecodevoid/voicechat-discord/issues/51#issuecomment-2172184678

**Comment by naturecodevoid** [comment]
Will be fixed in 3.0.0

**Comment by naturecodevoid** [comment]
3.0.0 is now out, which fixes this issue.

Paper/Purpur: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.0
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/zQYUpUdg
