### ISSUE TITLE
The mod do not work in 1.20.5

### ISSUE THREAD

**Issue by laroweb** [naturecodevoid/voicechat-discord#45]
Please help me the mod do not work what i can do ?

**Comment by laroweb** [comment]
I used the fabric mod [FABRIC] 2.1.1

**Comment by naturecodevoid** [comment]
It allows people with Simple Voice Chat installed on their client to talk in voice chat and hear voice chat through a discord voice channel and discord bot.

**Comment by laroweb** [comment]
![Capture d’écran 2024-05-04 011054](https://github.com/naturecodevoid/voicechat-discord/assets/50493428/4d21b8ad-55d3-44c6-beff-3ec6c33249e5)
When i do /dvc start

**Comment by naturecodevoid** [comment]
What’s in the console?

**Comment by laroweb** [comment]
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[19:54:30] [main/INFO]: Loading Minecraft 1.20.5 with Fabric Loader 0.15.10
[19:54:30] [main/INFO]: Loading 88 mods:
        - fabric-api 0.97.8+1.20.5
           |-- fabric-api-base 0.4.40+80f8cf510d
           |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72b0d
           |-- fabric-biome-api-v1 13.0.25+db2ee4240d
           |-- fabric-block-api-v1 1.0.20+6dfe4c9b0d
           |-- fabric-block-view-api-v2 1.0.8+80f8cf510d
           |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf510d
           |-- fabric-client-tags-api-v1 1.1.12+7f945d5b0d
           |-- fabric-command-api-v1 1.2.45+f71b366f0d
           |-- fabric-command-api-v2 2.2.24+80f8cf510d
           |-- fabric-commands-v0 0.2.62+df3654b30d
           |-- fabric-content-registries-v0 8.0.4+b82b23920d
           |-- fabric-convention-tags-v1 2.0.3+7f945d5b0d
           |-- fabric-convention-tags-v2 2.0.0+2b43c5c80d
           |-- fabric-crash-report-info-v1 0.2.27+80f8cf510d
           |-- fabric-data-attachment-api-v1 1.1.15+2a2c66b60d
           |-- fabric-data-generation-api-v1 19.0.6+7f945d5b0d
           |-- fabric-dimensions-v1 2.1.68+947939130d
           |-- fabric-entity-events-v1 1.6.8+e9d2a72b0d
           |-- fabric-events-interaction-v0 0.7.6+c5fc38b30d
           |-- fabric-game-rule-api-v1 1.0.50+80f8cf510d
           |-- fabric-item-api-v1 8.1.1+17e985d60d
           |-- fabric-item-group-api-v1 4.0.38+aae0949a0d
           |-- fabric-key-binding-api-v1 1.0.45+80f8cf510d
           |-- fabric-keybindings-v0 0.2.43+df3654b30d
           |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b30d
           |-- fabric-loot-api-v2 3.0.4+97f703da0d
           |-- fabric-message-api-v1 6.0.10+109a837c0d
           |-- fabric-model-loading-api-v1 1.0.12+80f8cf510d
           |-- fabric-models-v0 0.4.11+9386d8a70d
           |-- fabric-networking-api-v1 4.0.8+bd46f3a00d
           |-- fabric-object-builder-api-v1 15.1.3+c5fc38b30d
           |-- fabric-particles-v1 4.0.0+c5fc38b30d
           |-- fabric-recipe-api-v1 5.0.3+c5fc38b30d
           |-- fabric-registry-sync-v0 5.0.15+f1240ba70d
           |-- fabric-renderer-api-v1 3.2.12+97f703da0d
           |-- fabric-renderer-indigo 1.5.12+80f8cf510d
           |-- fabric-renderer-registries-v1 3.2.61+df3654b30d
           |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2e0d
           |-- fabric-rendering-fluids-v1 3.1.3+2c869ded0d
           |-- fabric-rendering-v0 1.1.64+df3654b30d
           |-- fabric-rendering-v1 4.2.4+b21c00cb0d
           |-- fabric-resource-conditions-api-v1 4.0.1+74e2f5600d
           |-- fabric-resource-loader-v0 1.0.5+c5f2432c0d
           |-- fabric-screen-api-v1 2.0.21+7b70ea8a0d
           |-- fabric-screen-handler-api-v1 1.3.72+b21c00cb0d
           |-- fabric-sound-api-v1 1.0.21+c5fc38b30d
           |-- fabric-transfer-api-v1 5.1.6+c5fc38b30d
           \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f5600d
        - fabricloader 0.15.10
           \-- mixinextras 0.3.5
        - floodgate 2.2.3-SNAPSHOT
           |-- aopalliance_aopalliance 1.0
           |-- cloud 2.0.0-SNAPSHOT
           |    |-- fabric-permissions-api-v0 0.3.1
           |    |-- io_leangen_geantyref_geantyref 1.3.15
           |    |-- org_incendo_cloud-brigadier 2.0.0-beta.6
           |    |-- org_incendo_cloud-core 2.0.0-beta.5
           |    |-- org_incendo_cloud-minecraft-modded-common-fabric-repack_ 2.0.0-SNAPSHOT
           |    \-- org_incendo_cloud-services 2.0.0-beta.5
           |-- jakarta_inject_jakarta_inject-api 2.0.1
           |-- javax_inject_javax_inject 1
           |-- org_geysermc_cumulus_cumulus 1.1.2
           |-- org_geysermc_event_events 1.1-SNAPSHOT
           |-- org_geysermc_geyser_common 2.2.3-SNAPSHOT
           |-- org_java-websocket_java-websocket 1.5.2
           \-- org_lanternpowered_lmbda 2.0.0
        - geyser-fabric 2.3.0-SNAPSHOT
           |-- com_fasterxml_jackson_core_jackson-annotations 2.17.0
           |-- com_fasterxml_jackson_core_jackson-core 2.17.0
           |-- com_fasterxml_jackson_core_jackson-databind 2.17.0
           |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.17.0
           |-- com_nukkitx_natives 1.0.3
           |-- io_airlift_aircompressor 0.25
           |-- io_netty_netty-codec-dns 4.1.107
           |-- io_netty_netty-codec-haproxy 4.1.107
           |-- io_netty_netty-resolver-dns-classes-macos 4.1.107
           |-- net_bytebuddy_byte-buddy 1.14.9
           |-- net_jodah_expiringmap 0.5.10
           |-- net_kyori_adventure-api 4.15.0
           |-- net_kyori_adventure-key 4.15.0
           |-- net_kyori_adventure-nbt 4.15.0
           |-- net_kyori_adventure-text-serializer-gson 4.15.0
           |-- net_kyori_adventure-text-serializer-json 4.15.0
           |-- net_kyori_adventure-text-serializer-json-legacy-impl 4.15.0
           |-- net_kyori_adventure-text-serializer-legacy 4.15.0
           |-- net_kyori_adventure-text-serializer-plain 4.15.0
           |-- net_kyori_examination-api 1.3.0
           |-- net_kyori_examination-string 1.3.0
           |-- net_kyori_option 1.0.0
           |-- org_bitbucket_b_c_jose4j 0.9.3
           |-- org_cloudburstmc_block-state-updater 1.20.80-20240411.142413-1
           |-- org_cloudburstmc_math_api 2.0
           |-- org_cloudburstmc_math_immutable 2.0
           |-- org_cloudburstmc_nbt 3.0.3
           |-- org_geysermc_api_base-api 1.0.0-SNAPSHOT
           |-- org_geysermc_cumulus_cumulus 1.1.2
           |-- org_geysermc_event_events 1.1-SNAPSHOT
           |-- org_lanternpowered_lmbda 2.0.0
           \-- org_yaml_snakeyaml 2.2
        - java 21
        - minecraft 1.20.5
        - voicechat 1.20.5-2.5.12
           \-- fabric-key-binding-api-v1 1.0.45+80f8cf51b2
        - voicechat-discord 2.1.1
[19:54:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[19:54:30] [main/INFO]: Compatibility level set to JAVA_17
[19:54:31] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[19:54:37] [main/INFO]: Loading extensions...
[19:54:37] [main/INFO]: Loaded 0 extension(s)
[19:54:37] [main/INFO]: [voicechat] Compatibility version 18
[19:54:37] [main/INFO]: [voicechat] Loading plugins
[19:54:37] [main/INFO]: [voicechat] Loaded 1 plugin(s)
[19:54:37] [main/INFO]: [voicechat] Initializing plugins
[19:54:37] [main/INFO]: Successfully initialized Simple Voice Chat plugin
[19:54:37] [main/INFO]: [voicechat] Initialized 1 plugin(s)
[19:54:37] [main/INFO]: [voicechat] Registering events for 'voicechat-discord'
[19:54:37] [main/INFO]: Using 1 bot
[19:54:37] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:54:39] [main/INFO]: Loaded 1175 recipes
[19:54:39] [main/INFO]: Loaded 1276 advancements
[19:54:40] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.444 ms
[19:54:40] [Server thread/INFO]: Starting minecraft server version 1.20.5
[19:54:40] [Server thread/INFO]: Loading properties
[19:54:40] [Server thread/INFO]: Default game type: SURVIVAL
[19:54:40] [Server thread/INFO]: Generating keypair
[19:54:40] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25511
[19:54:40] [Server thread/INFO]: Using epoll channel type
[19:54:40] [Server thread/INFO]: Preparing level "world"
[19:54:44] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:54:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[19:54:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[19:54:45] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[19:54:45] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[19:54:45] [Server thread/INFO]: Time elapsed: 1641 ms
[19:54:45] [Server thread/INFO]: Done (5.499s)! For help, type "help"
[19:54:45] [Server thread/INFO]: Took 25ms to boot Floodgate
[19:54:45] [Server thread/INFO]: ******************************************
[19:54:45] [Server thread/INFO]: 
[19:54:45] [Server thread/INFO]: Loading Geyser version 2.3.0-SNAPSHOT (git-master-8addcad)
[19:54:45] [Server thread/INFO]: 
[19:54:45] [Server thread/INFO]: ******************************************
[19:54:49] [epollEventLoopGroup-3-1/INFO]: Started Geyser on 0.0.0.0:25528
[19:54:49] [Server thread/INFO]: Done (3.242s)! Run /geyser help for help!
[19:54:49] [VoiceChatServerThread/INFO]: [voicechat] Using server-ip as bind address: 0.0.0.0
[19:54:49] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3320ms or 66 ticks behind
[19:54:49] [VoiceChatServerThread/INFO]: [voicechat] Voice chat server started at 0.0.0.0:25511
[19:55:13] [User Authenticator #1/INFO]: UUID of player Turbo5000 is e74c9edc-aeb4-4c02-9b26-f9463d34da04
[19:55:14] [Server thread/INFO]: Turbo5000[/184.162.196.149:52115] logged in with entity id 70 at (163.60400799382975, 80.0, -27.542947226477022)
[19:55:14] [Server thread/INFO]: [voicechat] Using Fabric Permissions API
[19:55:14] [Server thread/INFO]: Turbo5000 joined the game
[19:55:22] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
[19:55:22] [Server thread/INFO]: [STDERR]:      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
[19:55:22] [Server thread/INFO]: [STDERR]:      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
[19:55:22] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[19:55:22] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:124)
[19:55:22] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:80)
[19:55:22] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands.start(SubCommands.java:110)
[19:55:22] [Server thread/INFO]: [STDERR]:      at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[19:55:22] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_8865.method_54416(class_8865.java:29)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_8865.execute(class_8865.java:13)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_8856.method_54405(class_8856.java:8)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_8847.method_54388(class_8847.java:8)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_8854.method_54390(class_8854.java:107)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_54313(class_2170.java:381)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_9249(class_2170.java:311)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_58590(class_3244.java:1295)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_44356(class_3244.java:1283)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:162)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:841)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:168)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:136)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:823)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:817)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5383(class_1255.java:121)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:791)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696)
[19:55:22] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
[19:55:22] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by laroweb** [comment]
[](url)

https://github.com/naturecodevoid/voicechat-discord/assets/50493428/900483fc-94a1-46ab-96ef-832285432c56

not working

**Comment by naturecodevoid** [comment]
I’ll look into this next time I work on the mod. Looks like it isn’t compatible with newer versions

**Comment by laroweb** [comment]
Also how long do you think it will take to update the mod?

**Comment by naturecodevoid** [comment]
I am not actively working on this project so it may never be updated. I am, however, willing to review any PRs others make. See the project status update pinned issue.

As for making a discord server for support, I felt that GitHub Issues was sufficient for the few number of questions and issues I receive.

**Comment by naturecodevoid** [comment]
Update: https://github.com/naturecodevoid/voicechat-discord/issues/51#issuecomment-2172184678

**Comment by naturecodevoid** [comment]
Will be fixed in 3.0.0

**Comment by naturecodevoid** [comment]
3.0.0 is now out, which fixes this issue.

Paper/Purpur: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.0
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/zQYUpUdg
