### ISSUE TITLE
Mod can't interface with bots

### ISSUE THREAD

**Issue by MrAut0** [naturecodevoid/voicechat-discord#48]
Whenever the mod is added to my fabric 1.20.6 Minecraft server, before I add the bots and link them to my discord server, everything boots up fine and the console doesn't note any incompatibility errors. But the second I add a single bot to the server and then start it up, it spins up a huge error and doesn't let my server start.

**To Reproduce**
1. Start server with the mod installed and configured
2. Go to console after server crashed
3. See error

**Versions (please complete the following information):**
- Minecraft: 1.20.6
- Loader: Fabric
- Simple Voice Chat: 2.5.14
- Simple Voice Chat Discord Bridge: 2.1.1

Here's what the console's displaying:
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'voicechat-discord'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-1.20.4.jar:1.0.1]
Caused by: java.lang.RuntimeException: java.nio.file.AccessDeniedException: config/voicechat-discord.yml
	at dev.naturecodevoid.voicechatdiscord.Core.loadConfig(Core.java:77) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at dev.naturecodevoid.voicechatdiscord.Core.enable(Core.java:36) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at dev.naturecodevoid.voicechatdiscord.FabricMod.onInitializeServer(FabricMod.java:24) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.nio.file.AccessDeniedException: config/voicechat-discord.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482) ~[?:?]
	at java.base/java.nio.file.Files.newOutputStream(Files.java:227) ~[?:?]
	at dev.naturecodevoid.voicechatdiscord.shadow.yamlconfiguration.file.FileConfiguration.save(FileConfiguration.java:96) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at dev.naturecodevoid.voicechatdiscord.Core.loadConfig(Core.java:75) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at dev.naturecodevoid.voicechatdiscord.Core.enable(Core.java:36) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at dev.naturecodevoid.voicechatdiscord.FabricMod.onInitializeServer(FabricMod.java:24) ~[voicechat-discord-fabric-2.1.1%20(2).jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more

**Comment by naturecodevoid** [comment]
I think the mod is broken on 1.20.5+, there’s another issue about it

**Comment by naturecodevoid** [comment]
Update: https://github.com/naturecodevoid/voicechat-discord/issues/51#issuecomment-2172184678

**Comment by naturecodevoid** [comment]
@MrAut0 This is not an issue with the mod, but rather with your server setup. The mod appears not to have permissions to access the configuration file.
