### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by HarshSB20** [naturecodevoid/voicechat-discord#52]
Please add 1.21 support. Me and my friends have a server and we planned on using this plugin to chat with the bedrock players only to find out its outdated. I love the idea of this mod and hope you update it to 1.21.

**Comment by naturecodevoid** [comment]
Please see #52. Fixes are in progress but the fix I am prioritizing (which does not fix newer versions, but rather a long standing bug) may take a bit.

**Comment by HarshSB20** [comment]
Thanks for the quick response. I also wanted to inform you that when I used to use the paper version everything worked fine except for the discord users not being able to talk.

**Comment by naturecodevoid** [comment]
Sorry, not #52, I meant to say #51

**Comment by HarshSB20** [comment]
The error i recieve when doing /dvc start is an unexpected error occured when trying to execute that command. Here is what popped up in the logs 

[04:21:33] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
[04:21:33] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:124)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:80)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.stop(SubCommands.java:132)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.method_54416(class_8865.java:29)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.execute(class_8865.java:13)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8856.method_54405(class_8856.java:8)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8847.method_54388(class_8847.java:8)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8854.method_54390(class_8854.java:107)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_54313(class_2170.java:379)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:309)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1348)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_58588(class_3244.java:1329)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:145)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
[04:21:33] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[04:21:41] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
[04:21:41] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:124)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:74)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.reloadConfig(SubCommands.java:150)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.method_54416(class_8865.java:29)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.execute(class_8865.java:13)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8856.method_54405(class_8856.java:8)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8847.method_54388(class_8847.java:8)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8854.method_54390(class_8854.java:107)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_54313(class_2170.java:379)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:309)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1348)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_58588(class_3244.java:1329)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:121)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
[04:21:41] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[04:21:47] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
[04:21:47] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:124)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:80)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.start(SubCommands.java:110)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.method_54416(class_8865.java:29)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.execute(class_8865.java:13)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8856.method_54405(class_8856.java:8)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8847.method_54388(class_8847.java:8)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8854.method_54390(class_8854.java:107)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_54313(class_2170.java:379)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:309)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1348)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_58588(class_3244.java:1329)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:121)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
[04:21:47] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[04:21:57] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
[04:21:57] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:124)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:80)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.start(SubCommands.java:110)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.method_54416(class_8865.java:29)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8865.execute(class_8865.java:13)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8856.method_54405(class_8856.java:8)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8847.method_54388(class_8847.java:8)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8854.method_54390(class_8854.java:107)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_54313(class_2170.java:379)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:309)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1348)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_58588(class_3244.java:1329)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:121)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
[04:21:57] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by HarshSB20** [comment]
I'm pretty sure this is because I'm on 1.21.

**Comment by naturecodevoid** [comment]
Will be fixed in 3.0.0

**Comment by HarshSB20** [comment]
Okay thanks. Is there an ETA for the 3.0.0. If not thats fine.

**Comment by naturecodevoid** [comment]
No. I will comment on each of the fixed issues when it is released. See #51 for more info

**Comment by naturecodevoid** [comment]
@HarshSB20

3.0.0 is now out, which fixes this issue.

Paper/Purpur: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.0
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/zQYUpUdg
